-- CNM Group OS — target relational schema (PostgreSQL 15+ / Supabase).
-- Design reference for docs/ADMIN-OS-SPEC.md. NOT applied automatically: the live system still runs on the cnm_kv
-- document store (supabase/migrations/20260927000000_cnm_store.sql). Migrate module by module (spec §13).
--
-- Conventions
--   * Every tenant-owned row carries company_id → data is isolated per company; group reports aggregate across them.
--   * Money is bigint minor units (kobo, cents) + currency; never floats.
--   * ids are uuid v7 (time-ordered) generated by the app; human numbers (order_number) are separate and unique.
--   * created_at/updated_at timestamptz; soft delete via archived_at (hard delete only for GDPR/NDPR erasure).
--   * Row Level Security on every table; server functions use the service role; staff access via staff_company_roles.

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ============================================================================ Tenancy
create table companies (
  id              text primary key check (id ~ '^[a-z0-9][a-z0-9-]{1,39}$'),
  name            text not null unique,
  kind            text not null check (kind in ('retail','services','engineering','nonprofit','marketplace','digital')),
  status          text not null default 'active' check (status in ('active','archived')),
  logo_url        text,
  brand_color     text not null check (brand_color ~ '^#[0-9a-f]{6}$'),
  currency        char(3) not null default 'NGN',
  timezone        text not null default 'Africa/Lagos',
  legal_name      text, rc_number text, tax_id text,
  settings        jsonb not null default '{}',          -- feature flags, SLA overrides, invoice footer…
  created_at      timestamptz not null default now(), created_by uuid, updated_at timestamptz, updated_by uuid, archived_at timestamptz
);
create table company_domains       (company_id text references companies, domain citext primary key, is_primary boolean not null default false, verified_at timestamptz);
create table company_payment_methods (company_id text references companies, method text not null, provider text not null, config jsonb not null default '{}', enabled boolean not null default true, primary key (company_id, method));
create table company_delivery_options (company_id text references companies, option_id text not null, label text not null, fee_minor bigint not null default 0, regions text[] not null default '{*}', eta_days int4range, enabled boolean not null default true, primary key (company_id, option_id));
create table brands   (id uuid primary key, company_id text not null references companies, name text not null, slug text not null, logo_url text, unique (company_id, slug));
create table channels (id text primary key, label text not null);  -- web, app, manual, pos, marketplace:<name>
create table locations (id uuid primary key, company_id text not null references companies, kind text not null check (kind in ('store','warehouse','pickup_point','office')),
  name text not null, address jsonb not null, region text, country char(2) not null default 'NG', geo point, hours jsonb, archived_at timestamptz);

-- ============================================================================ Staff, roles, security
create table staff (id uuid primary key, email citext not null unique, name text not null, status text not null default 'active' check (status in ('invited','active','suspended')),
  password_hash text, totp_secret_enc bytea, totp_enabled_at timestamptz, webauthn jsonb, last_login_at timestamptz, created_at timestamptz not null default now());
create table roles (id text primary key, label text not null, is_system boolean not null default false);          -- super_admin, group_finance, company_admin, ops, fulfilment, support, marketing, editor, analyst
create table permissions (id text primary key, area text not null, description text not null);                     -- e.g. orders.read, orders.refund, products.write, finance.export
create table role_permissions (role_id text references roles, permission_id text references permissions, primary key (role_id, permission_id));
-- company_id null = group-wide grant (super admin / group finance). Otherwise scoped to one company.
create table staff_company_roles (id uuid primary key default gen_random_uuid(), staff_id uuid not null references staff, company_id text references companies, role_id text not null references roles,
  granted_by uuid, granted_at timestamptz not null default now());
create unique index on staff_company_roles (staff_id, coalesce(company_id, '*'), role_id);
create table staff_sessions (id uuid primary key, staff_id uuid not null references staff, created_at timestamptz not null default now(), last_seen_at timestamptz, expires_at timestamptz not null,
  ip inet, user_agent text, mfa_at timestamptz, revoked_at timestamptz, revoked_reason text);
create index on staff_sessions (staff_id) where revoked_at is null;

-- Append-only audit log. Each row hashes the previous row → tampering is detectable. No UPDATE/DELETE grants.
create table audit_log (id bigint generated always as identity primary key, at timestamptz not null default now(), staff_id uuid, staff_email citext, role text, company_id text,
  action text not null, entity text, entity_id text, before jsonb, after jsonb, reason text, ip inet, user_agent text, request_id text, prev_hash bytea, hash bytea not null);
create index on audit_log (company_id, at desc);
create index on audit_log (entity, entity_id);
create index on audit_log (staff_id, at desc);

create table idempotency_keys (scope text not null, key text not null, fingerprint bytea not null, response jsonb not null, status int not null, created_at timestamptz not null default now(),
  primary key (scope, key));  -- purge after 24 h

-- ============================================================================ Catalogue
create table categories (id uuid primary key, company_id text not null references companies, parent_id uuid references categories, name text not null, slug text not null, position int not null default 0, unique (company_id, slug));
create table products (id uuid primary key, company_id text not null references companies, brand_id uuid references brands, category_id uuid references categories,
  title text not null, slug text not null, description text, status text not null default 'draft' check (status in ('draft','scheduled','active','archived')),
  launch_at timestamptz, flags text[] not null default '{}',            -- new, bestseller, limited, exclusive, price_needs_approval
  seo jsonb not null default '{}', attributes jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz, unique (company_id, slug));
create index on products (company_id, status);
create table product_variants (id uuid primary key, product_id uuid not null references products on delete cascade, company_id text not null,
  sku text not null, barcode text, options jsonb not null default '{}',   -- {"size":"100ml","scent":"Vanilla"}
  price_minor bigint not null, compare_at_minor bigint, cost_minor bigint, currency char(3) not null, weight_g int, status text not null default 'active',
  unique (company_id, sku));
create unique index on product_variants (company_id, barcode) where barcode is not null;
create table price_schedules (id uuid primary key, variant_id uuid not null references product_variants, price_minor bigint not null, starts_at timestamptz not null, ends_at timestamptz, created_by uuid);
create table media (id uuid primary key, company_id text not null references companies, url text not null, kind text not null, alt text, width int, height int, bytes int, created_at timestamptz not null default now());
create table product_media (product_id uuid references products on delete cascade, media_id uuid references media, position int not null default 0, primary key (product_id, media_id));

-- ============================================================================ Inventory
create table inventory_levels (variant_id uuid references product_variants, location_id uuid references locations, company_id text not null,
  on_hand int not null default 0, reserved int not null default 0 check (reserved >= 0), incoming int not null default 0, reorder_point int not null default 5,
  updated_at timestamptz not null default now(), primary key (variant_id, location_id), check (on_hand >= 0));
-- available = on_hand − reserved (computed). Reservations are taken at checkout, released on payment failure/expiry, consumed on dispatch.
create table inventory_movements (id bigint generated always as identity primary key, company_id text not null, variant_id uuid not null, location_id uuid not null,
  kind text not null check (kind in ('receive','sale','reserve','release','return','adjust','transfer_out','transfer_in','count')),
  qty int not null, reason text, ref_type text, ref_id text, by_staff uuid, at timestamptz not null default now());
create index on inventory_movements (variant_id, at desc);
create table stock_transfers (id uuid primary key, company_id text not null, from_location uuid not null, to_location uuid not null, status text not null check (status in ('draft','in_transit','received','cancelled')),
  lines jsonb not null, created_by uuid, created_at timestamptz not null default now(), received_at timestamptz);

-- ============================================================================ Customers
create table customers (id uuid primary key, email citext, phone text, first_name text, last_name text, created_at timestamptz not null default now(),
  marketing_email boolean not null default false, marketing_sms boolean not null default false, tags text[] not null default '{}', erased_at timestamptz);
create unique index on customers (email) where email is not null and erased_at is null;
-- Group-level customer identity; per-company relationship (LTV, notes, segments) lives here:
create table customer_companies (customer_id uuid references customers, company_id text references companies, first_order_at timestamptz, last_order_at timestamptz,
  orders_count int not null default 0, ltv_minor bigint not null default 0, notes text, segment text, primary key (customer_id, company_id));
create table addresses (id uuid primary key, customer_id uuid references customers on delete cascade, label text, line1 text not null, line2 text, city text not null, state text not null, country char(2) not null default 'NG', phone text, is_default boolean default false);
create table carts (id uuid primary key, company_id text not null, customer_id uuid, email citext, lines jsonb not null, subtotal_minor bigint not null, updated_at timestamptz not null default now(),
  recovered_order_id uuid, recovery_sent_at timestamptz);                  -- abandoned = no order and updated_at > 1 h ago
create table wishlist_items (customer_id uuid references customers, variant_id uuid references product_variants, company_id text not null, added_at timestamptz not null default now(), primary key (customer_id, variant_id));
create table reviews (id uuid primary key, company_id text not null, product_id uuid not null references products, customer_id uuid, order_id uuid, rating smallint not null check (rating between 1 and 5),
  title text, body text, status text not null default 'pending' check (status in ('pending','published','rejected')), moderated_by uuid, moderated_at timestamptz, created_at timestamptz not null default now());

-- ============================================================================ Orders, payments, fulfilment
create table orders (id uuid primary key, company_id text not null references companies, order_number text not null unique, channel text not null references channels,
  customer_id uuid references customers, email citext not null, phone text,
  status text not null check (status in ('pending_payment','paid','processing','ready','dispatched','delivered','cancelled','returned','refunded','partially_refunded','payment_failed')),
  currency char(3) not null, subtotal_minor bigint not null, discount_minor bigint not null default 0, shipping_minor bigint not null default 0, tax_minor bigint not null default 0,
  total_minor bigint not null, refunded_minor bigint not null default 0, promo_code text, shipping_address jsonb, pickup_location uuid references locations,
  notes text, risk_score smallint, risk_status text default 'clear' check (risk_status in ('clear','review','blocked')), placed_by_staff uuid,    -- manual orders
  created_at timestamptz not null default now(), updated_at timestamptz, paid_at timestamptz, cancelled_at timestamptz);
create index on orders (company_id, created_at desc);
create index on orders (company_id, status) where status in ('pending_payment','paid','processing','ready','dispatched');
create index on orders (customer_id, created_at desc);
create table order_lines (id uuid primary key, order_id uuid not null references orders on delete cascade, variant_id uuid, sku text not null, title text not null, qty int not null check (qty > 0),
  unit_price_minor bigint not null, discount_minor bigint not null default 0, tax_minor bigint not null default 0, total_minor bigint not null, fulfilled_qty int not null default 0, returned_qty int not null default 0);
create table order_events (id bigint generated always as identity primary key, order_id uuid not null references orders, status text not null, at timestamptz not null default now(), by_actor text, note text);
create table payments (id uuid primary key, order_id uuid not null references orders, company_id text not null, provider text not null, method text not null, reference text not null unique,
  status text not null check (status in ('pending','authorized','paid','failed','refunded','partially_refunded','disputed')), amount_minor bigint not null, fee_minor bigint, currency char(3) not null,
  paid_at timestamptz, raw jsonb, settlement_id uuid);
create table refunds (id uuid primary key, order_id uuid not null references orders, payment_id uuid not null references payments, amount_minor bigint not null check (amount_minor > 0),
  reason text not null, status text not null check (status in ('requested','approved','processing','succeeded','failed','rejected')), provider_ref text,
  requested_by uuid, approved_by uuid, created_at timestamptz not null default now(), completed_at timestamptz);
create table settlements (id uuid primary key, company_id text not null, provider text not null, provider_ref text not null unique, period daterange not null,
  gross_minor bigint not null, fees_minor bigint not null, refunds_minor bigint not null, net_minor bigint not null, paid_out_at timestamptz, reconciled_at timestamptz, discrepancy_minor bigint default 0);
create table tax_rates (id uuid primary key, company_id text, country char(2) not null, region text, name text not null, rate numeric(6,4) not null, inclusive boolean not null default true, valid daterange not null);

create table couriers (id text primary key, name text not null, api jsonb, tracking_url_template text);                    -- gig, dhl, kwik, sendbox, in_house
create table shipments (id uuid primary key, order_id uuid not null references orders, company_id text not null, courier_id text references couriers, tracking_number text,
  status text not null check (status in ('awaiting_fulfilment','packed','handed_over','in_transit','out_for_delivery','delivered','failed_attempt','rescheduled','returned_to_sender','lost')),
  from_location uuid references locations, eta date, promised_by date, delivered_at timestamptz, attempts int not null default 0,
  proof_of_delivery jsonb,                                                                     -- {photo_url, signature_url, recipient, geo}
  lines jsonb not null, created_at timestamptz not null default now());
create index on shipments (company_id, status);
create table shipment_events (id bigint generated always as identity primary key, shipment_id uuid not null references shipments, status text not null, at timestamptz not null, location text, note text, source text not null);
create table delivery_exceptions (id uuid primary key, shipment_id uuid not null references shipments, kind text not null, opened_at timestamptz not null default now(), resolved_at timestamptz, resolution text, owner uuid);

create table returns (id uuid primary key, order_id uuid not null references orders, company_id text not null, rma_number text not null unique,
  status text not null check (status in ('requested','approved','rejected','in_transit','received','inspected','refunded','exchanged','closed')),
  kind text not null check (kind in ('refund','exchange','store_credit')), reason text not null, lines jsonb not null, refund_id uuid references refunds, exchange_order_id uuid references orders,
  approved_by uuid, created_at timestamptz not null default now());

-- ============================================================================ Marketing, content, notifications, risk
create table promotions (id uuid primary key, company_id text not null, kind text not null check (kind in ('coupon','automatic','bundle','flash_sale','bogo','free_shipping')),
  name text not null, rules jsonb not null, starts_at timestamptz, ends_at timestamptz, usage_limit int, per_customer_limit int, used int not null default 0, status text not null default 'draft');
create table coupon_codes (code citext primary key, promotion_id uuid not null references promotions, company_id text not null);
create table referrals (id uuid primary key, company_id text not null, referrer_customer uuid, code text not null unique, reward jsonb, conversions int not null default 0);
create table campaigns (id uuid primary key, company_id text not null, name text not null, channel text not null, utm jsonb, budget_minor bigint, starts_at timestamptz, ends_at timestamptz);
create table content_blocks (id uuid primary key, company_id text not null, page text not null, slot text not null, kind text not null, data jsonb not null,
  status text not null default 'draft' check (status in ('draft','scheduled','published')), publish_at timestamptz, version int not null default 1, updated_by uuid, updated_at timestamptz);
create table navigation (company_id text references companies, menu text, items jsonb not null, primary key (company_id, menu));
create table notification_templates (id uuid primary key, company_id text, channel text not null check (channel in ('email','sms','push','whatsapp')), event text not null,
  locale text not null default 'en-NG', subject text, body text not null, version int not null default 1, active boolean not null default true);
create table notification_log (id bigint generated always as identity primary key, company_id text, channel text not null, template_id uuid, recipient text not null, status text not null, provider_ref text, at timestamptz not null default now(), error text);
create table risk_rules (id uuid primary key, company_id text, name text not null, condition jsonb not null, action text not null check (action in ('flag','review','block')), score smallint not null, enabled boolean not null default true);
create table risk_flags (id uuid primary key, order_id uuid references orders, rule_id uuid references risk_rules, score smallint not null, status text not null default 'open' check (status in ('open','cleared','confirmed')),
  reviewed_by uuid, reviewed_at timestamptz, created_at timestamptz not null default now());

-- ============================================================================ Analytics
-- Raw events (partitioned by month) → rolled up into daily_metrics every 5 minutes; dashboards read rollups only.
create table events (id bigint generated always as identity, company_id text not null, at timestamptz not null, name text not null, session_id text, anon_id text, customer_id uuid,
  path text, product_id uuid, props jsonb, primary key (at, id)) partition by range (at);
create table daily_metrics (company_id text not null, day date not null, channel text not null default 'all', location text not null default 'all',
  active_users int, sessions int, product_views int, add_to_carts int, checkouts int, orders int, units int,
  gross_minor bigint, discounts_minor bigint, refunds_minor bigint, net_minor bigint, shipping_minor bigint, tax_minor bigint,
  delivered int, failed_deliveries int, primary key (company_id, day, channel, location));
create table product_daily_metrics (company_id text not null, product_id uuid not null, day date not null, views int, add_to_carts int, units int, revenue_minor bigint, primary key (product_id, day));
create table saved_reports (id uuid primary key, owner uuid references staff, company_id text, name text not null, query jsonb not null, schedule text, recipients citext[], last_run_at timestamptz);

-- ============================================================================ Outbox (real-time + integrations)
-- Written in the same transaction as the state change; a worker publishes to Realtime/webhooks exactly once per id.
create table outbox (id bigint generated always as identity primary key, company_id text, topic text not null, payload jsonb not null, created_at timestamptz not null default now(), published_at timestamptz);
create index on outbox (created_at) where published_at is null;

-- RLS pattern (repeat for every tenant table):
--   alter table orders enable row level security;
--   create policy staff_read on orders for select using (exists (select 1 from staff_company_roles r where r.staff_id = auth.uid() and (r.company_id is null or r.company_id = orders.company_id)));
